Repository coala/gh-board, pull requests merged in 2018-10, with the labels that each got.

#164 src/router.jsx: Change browserHistory to history
  src/router.jsx
Labels: importance/medium, process/pending review, size/XS

#168 moban: Sync Moban Templates
  .gitignore
Labels: process/approved, size/XS

#167 github-graphql.js: Change console message.
  src/github-graphql.js
Labels: difficulty/newcomer, importance/low, process/pending review, size/XS

#170 .gitignore: Sync moban templates
  .gitignore
Labels: process/approved, size/XS

#169 app.less: Remove unused .game-modal
  style/app.less
Labels: difficulty/newcomer, importance/medium, process/approved, size/XS

#175 nav.jsx: Remove menu to star repo
  src/components/app/nav.jsx
Labels: difficulty/low, importance/low, initiatives/gci, process/approved, size/XS
