Repository coala/gh-board, pull requests merged in 2018-08, with the labels that each got.

#83 Add review filters functionality
  src/components/app/filter-dropdown.jsx
  src/components/repo-kanban.jsx
  src/filter-store.js
  src/github-client.js
  src/route-utils.js
Labels: enhancement, process/approved, size/S

#144 .travis.yml: Remove duplicate before_install
  .travis.yml
Labels: process/approved, size/XS

#142 Netlify build: Verify pre-fetched files exist
  netlify.toml
  script/run-test.sh
  script/verify-files.sh
Labels: importance/medium, process/pending review, size/XS, type/feature

#128 Enhance meta-review UI
  src/components/reactions.jsx
  src/components/review-blurb.jsx
  style/review.less
  test/src/components/__snapshots__/reactions.test.js.snap
Labels: difficulty/low, enhancement, process/approved, size/XS

#150 Fix review fetch ignore settings
  script/fetch-issues.js
  src/github-client.js
Labels: enhancement, importance/medium, process/pending review, size/XS

#153 README.md: Add meta-review section
  README.md
Labels: enhancement, process/approved, size/XS

#155 webpack.config.js: Enable source map in prod
  webpack.config.js
Labels: importance/medium, process/approved, size/XS

#156 Sync gitignore list
  .gitignore
Labels: process/approved, size/XS

#159 issue-blurb.jsx: Remove unnecessary onClick attribute
  src/components/issue-blurb.jsx
Labels: difficulty/low, importance/medium, process/pending review, size/XS
