Repository coala/gh-board, pull requests merged in 2018-07, with the labels that each got.

#69 Sync gitignore
  .gitignore
Labels: importance/medium, process/approved, size/XS, type/feature

#73 .travis.yml: Enable keep-history
  .travis.yml
Labels: enhancement, process/approved, size/XS, type/feature

#75 run-test.sh: Verify files exist
  .travis.yml
  script/run-test.sh
Labels: bug, importance/medium, process/approved, size/XS

#80 login-modal.jsx: Add exception for default api url
  src/components/login-modal.jsx
Labels: process/approved, size/XS

#81 dashboard.jsx: Add environment REPOSITORIES
  src/components/dashboard.jsx
  webpack.config.js
Labels: difficulty/low, process/approved, size/XS

#124 README.md: Fix minor table of contents inconsistencies
  README.md
Labels: process/approved, size/XS

#85 script/: Set -x -e on shell scripts
  script/build.sh
  script/run-build-and-then-test.sh
Labels: process/approved, size/XS

#135 Fix /dashboard routing
  src/router.jsx
Labels: process/approved, size/XS
