Repository coala/gh-board, pull requests merged in 2018-06, with the labels that each got.

#46 package.json: Add linting on script & test
  package.json
  test/index.js
Labels: difficulty/low, importance/medium, process/approved, size/XS

#44 Use gitignore moban
  .ci/check_moban.sh
  .gitignore
  .moban.dt/gh-board-gitignore.jj2
  .moban.yaml
  .travis.yml
Labels: process/approved, size/L

#51 .travis.yml: Update gitignore deploy exception
  .travis.yml
Labels: importance/medium, process/approved, size/XS

#56 Sync gitignore list
  .gitignore
Labels: process/approved, size/XS

#54 README.md: Remove Easter egg section
  README.md
Labels: difficulty/newcomer, process/pending review, size/XS

#58 Set pre-fetch time limit for pull requests
  package-lock.json
  package.json
  script/fetch-issues.js
Labels: importance/medium, process/approved, size/XS, type/feature
