Repository coala/gh-board, pull requests merged in 2018-05, with the labels that each got.

#21 .travis.yml: Enable travis-buddy
  .travis.yml
Labels: process/pending review, size/XS

#18 fetch-issues.js: Build custom generator
  package-lock.json
  package.json
  script/build.sh
  script/fetch-issues.js
  script/queries/github_issue_info.graphql
  script/queries/github_label_info.graphql
  script/queries/github_pr_info.graphql
  script/queries/index.js
Labels: bug, process/approved, size/XL

#7 .travis.yml: Enable caching
  .travis.yml
Labels: process/approved, size/XS

#33 Remove TODOs in components code
  src/components/app/filter-dropdown.jsx
  src/components/by-milestone-view.jsx
  src/components/repo-kanban.jsx
Labels: process/approved, size/XS

#41 nav.jsx: Fix broken link on header
  src/components/app/nav.jsx
Labels: bug, process/approved, size/XS

#39 Pre-fetch pull request review comments & reactions
  package-lock.json
  package.json
  script/fetch-issues.js
  script/queries/github_pr_info.graphql
  script/queries/github_reaction_info.graphql
  script/queries/index.js
  src/initial-data.js
Labels: process/approved, size/M
